export type SourceStatus = "attiva" | "integrazione" | "mappata";

export type PublicSource = {
  slug: string;
  name: string;
  owner: string;
  area: string;
  cadence: string;
  coverage: string;
  format: string;
  url: string;
  status: SourceStatus;
  note: string;
  joinKeys?: string[];
};

export const publicSources: PublicSource[] = [
  {
    slug: "siope",
    name: "SIOPE / SIOPE+",
    owner: "RGS · Banca d'Italia",
    area: "Incassi e pagamenti PA",
    cadence: "Controllo orario dei file; aggiornamento quando cambia la fonte",
    coverage: "Adapter attivo: pagamenti di cassa dei Comuni",
    format: "ZIP · CSV · classificazioni contabili",
    url: "https://www.siope.it/documenti/siope2/open/last/",
    status: "attiva",
    note: "Fonte primaria attiva: movimenti mensili nazionali, anagrafiche SIOPE, snapshot comunale versionato e dashboard territoriale.",
  },
  {
    slug: "openbdap",
    name: "OpenBDAP",
    owner: "Ragioneria Generale dello Stato",
    area: "Bilancio, spesa, SIOPE, opere, PNRR",
    cadence: "Variabile per dataset; pagamenti Stato per mese contabile",
    coverage: "Catalogo nazionale RGS",
    format: "CKAN API · CSV · open data",
    url: "https://bdap-opendata.rgs.mef.gov.it/content/api",
    status: "attiva",
    note: "Connettore attivo: catalogo, pagamenti dello Stato, missioni, amministrazioni, classificazione economica e serie 2026.",
  },
  {
    slug: "anac-bdncp",
    name: "BDNCP / ANAC Open Data",
    owner: "ANAC",
    area: "Contratti e appalti pubblici",
    cadence: "Dataset aperti mensili; Analytics con cadenza distinta",
    coverage: "Contratti pubblici nazionali",
    format: "Open data · CSV/JSON · ricerca CIG",
    url: "https://www.anticorruzione.it/-/portale-dei-dati-aperti-dell-autorita-nazionale-anticorruzione",
    status: "integrazione",
    note: "Per procedure, CIG, stazioni appaltanti, aggiudicazioni, fornitori e ciclo di vita dei contratti.",
  },
  {
    slug: "art-4-bis",
    name: "Pagamenti art. 4-bis",
    owner: "Singole amministrazioni · schema ANAC",
    area: "Pagamenti per tipologia e beneficiario",
    cadence: "Secondo pubblicazione dell'ente",
    coverage: "Amministrazioni soggette al D.Lgs. 33/2013",
    format: "JSON · CSV · XML · PDF",
    url: "https://guida-servizi.anticorruzione.it/it/help/trasparenza/schemi/art.4-bis/",
    status: "integrazione",
    note: "Schema 2026 che rende possibile un crawler nazionale normalizzato dei dati sui pagamenti.",
  },
  {
    slug: "ipa",
    name: "Indice PA (IPA)",
    owner: "AgID",
    area: "Anagrafe degli enti",
    cadence: "Giornaliera",
    coverage: "PA, gestori di servizi pubblici e altri soggetti censiti",
    format: "JSON · XLSX · Data API",
    url: "https://www.indicepa.gov.it/ipa-dati/dataset/enti",
    status: "attiva",
    note: "Connettore attivo: ricerca enti, pagina canonica per Codice IPA, API normalizzata e aggregazioni reali.",
    joinKeys: ["Codice IPA", "codice fiscale", "codice ISTAT"],
  },
  {
    slug: "ipa-struttura",
    name: "IPA · UO e AOO",
    owner: "AgID",
    area: "Articolazioni interne e protocolli",
    cadence: "Giornaliera",
    coverage: "Unità Organizzative e Aree Organizzative Omogenee degli enti IPA",
    format: "CKAN Data API · XLSX · JSON",
    url: "https://www.indicepa.gov.it/ipa-dati/dataset/unita-organizzative",
    status: "attiva",
    note: "Connettore attivo nelle schede ente: UO, relazioni padre-figlio dichiarate da IPA e AOO. Non sostituisce i regolamenti di organizzazione dei singoli enti.",
    joinKeys: ["Codice IPA", "Codice UO", "Codice AOO"],
  },
  {
    slug: "opencoesione",
    name: "OpenCoesione",
    owner: "Dipartimento per le Politiche di Coesione",
    area: "Progetti e pagamenti di coesione",
    cadence: "Bimestrale prevista per i principali dataset",
    coverage: "Aggregato nazionale per stati, temi e nature",
    format: "API · CSV · open data",
    url: "https://opencoesione.gov.it/it/opendata/",
    status: "attiva",
    note: "Dashboard nazionale attiva; nessun drill-down per progetto, soggetto o territorio. Aggiornamento automatico dall'API ufficiale.",
  },
  {
    slug: "istat-s13",
    name: "Classificazione ISTAT S13",
    owner: "ISTAT · distribuzione OpenBDAP/RGS",
    area: "Perimetro delle amministrazioni pubbliche",
    cadence: "Annuale; aggiornamenti anagrafici OpenBDAP distinti",
    coverage: "Unità istituzionali incluse nel settore S13",
    format: "OpenBDAP · documentazione e dataset",
    url: "https://bdap-opendata.rgs.mef.gov.it/content/anagrafica-enti-classificazione-istat-s13",
    status: "mappata",
    note: "Fonte censita, senza adapter machine-readable attivo. IPA e S13 descrivono perimetri diversi: l'appartenenza al settore S13 non viene inferita dalla sola presenza in IPA.",
    joinKeys: ["codice fiscale", "codice ente RGS"],
  },
  {
    slug: "partecipazioni-pubbliche",
    name: "Censimento partecipazioni pubbliche",
    owner: "MEF · Dipartimento dell'Economia",
    area: "Società partecipate e rapporti di partecipazione",
    cadence: "Rilevazione annuale",
    coverage: "Partecipazioni dichiarate dalle amministrazioni e società partecipate",
    format: "Open data elaborabile · rilevazioni annuali",
    url: "https://www.de.mef.gov.it/it/attivita_istituzionali/partecipazioni_pubbliche/open_data_partecipazioni/index.html",
    status: "attiva",
    note: "Snapshot nazionale attivo: 53.656 relazioni della rilevazione 2023, aggregati e organizzazioni dichiarate da più amministrazioni. Il drill-down completo per singola relazione richiede il successivo indice persistente.",
    joinKeys: ["codice fiscale amministrazione", "codice fiscale società"],
  },
  {
    slug: "partecipazioni-stato",
    name: "Partecipazioni dirette dello Stato",
    owner: "MEF · Dipartimento dell'Economia",
    area: "Partecipazioni societarie del Tesoro",
    cadence: "Secondo pubblicazione istituzionale",
    coverage: "Società partecipate direttamente dal Ministero dell'Economia e delle Finanze",
    format: "Web · documenti istituzionali",
    url: "https://www.de.mef.gov.it/it/attivita_istituzionali/partecipazioni/elenco_partecipazioni/",
    status: "mappata",
    note: "Fonte distinta dal censimento di tutte le partecipazioni pubbliche. Non viene usata per dedurre automaticamente controllo o natura in-house.",
  },
  {
    slug: "anac-in-house-storico",
    name: "Elenco ANAC in-house · storico",
    owner: "ANAC",
    area: "Affidamenti diretti a organismi in-house",
    cadence: "Archivio cessato il 30 giugno 2023",
    coverage: "Iscrizioni e provvedimenti dell'elenco ex art. 192 fino alla sua cessazione",
    format: "Avviso ufficiale · provvedimenti storici",
    url: "https://www.anticorruzione.it/-/adempimenti-art.-192-del-d.lgs.-n.-50/2016",
    status: "mappata",
    note: "ANAC dichiara l'elenco non più operativo dal 1° luglio 2023. Può fornire evidenza storica, mai un badge corrente di società in-house.",
    joinKeys: ["codice fiscale amministrazione", "codice fiscale organismo"],
  },
  {
    slug: "anac-ausa",
    name: "AUSA · Stazioni appaltanti",
    owner: "ANAC",
    area: "Anagrafe delle stazioni appaltanti",
    cadence: "Aggiornamento identificativi almeno annuale",
    coverage: "Stazioni appaltanti e centri di costo censiti da ANAC",
    format: "Open data · CSV/JSON/TTL",
    url: "https://www.anticorruzione.it/-/anagrafe-unica-delle-stazioni-appaltanti-ausa-",
    status: "mappata",
    note: "Fonte identificativa utile per collegare le stazioni appaltanti. L'iscrizione AUSA non dimostra che un ente o una società sia in-house.",
    joinKeys: ["codice AUSA", "codice fiscale"],
  },
  {
    slug: "regis",
    name: "ReGiS / PNRR Open Data",
    owner: "MEF · Italia Domani / catalogo nazionale",
    area: "PNRR",
    cadence: "Estratti periodici",
    coverage: "Progetti finanziati dal PNRR",
    format: "Open data",
    url: "https://open.gov.it/governo-aperto/piano-nazionale/6nap/azione-3/impegno-6",
    status: "mappata",
    note: "Dati finanziari, fisici e procedurali dei progetti PNRR pubblicati come estrazioni dal sistema ReGiS.",
  },
  {
    slug: "consulenti",
    name: "Consulenti Pubblici",
    owner: "Dipartimento della Funzione Pubblica",
    area: "Consulenze e incarichi",
    cadence: "Aggiornamento per singolo incarico/amministrazione",
    coverage: "Incarichi comunicati dalle amministrazioni",
    format: "Ricerca · export open data",
    url: "https://consulentipubblici.dfp.gov.it/",
    status: "mappata",
    note: "Compenso lordo, ammontare erogato e dati sugli incarichi esterni e ai dipendenti PA.",
  },
  {
    slug: "camera",
    name: "Camera Trasparente",
    owner: "Camera dei deputati",
    area: "Parlamento",
    cadence: "Secondo pubblicazione istituzionale",
    coverage: "Bilancio e amministrazione della Camera",
    format: "Web · documenti",
    url: "https://trasparenza.camera.it/",
    status: "mappata",
    note: "Bilanci, procedure di gara, organizzazione e trattamento economico secondo quanto pubblicato dalla Camera.",
  },
  {
    slug: "senato",
    name: "Spese e trasparenza",
    owner: "Senato della Repubblica",
    area: "Parlamento",
    cadence: "Secondo pubblicazione istituzionale",
    coverage: "Bilancio e amministrazione del Senato",
    format: "Web · documenti",
    url: "https://www.senato.it/relazioni-con-i-cittadini/spese-trasparenza/spese-e-trasparenza",
    status: "mappata",
    note: "Bilancio, consuntivo e informazioni ufficiali sul trattamento economico dei senatori.",
  },
];

export const sourceCounts = {
  total: publicSources.length,
  active: publicSources.filter((source) => source.status === "attiva").length,
  integrating: publicSources.filter((source) => source.status === "integrazione").length,
  mapped: publicSources.filter((source) => source.status === "mappata").length,
};
